#!/usr/bin python

from fabric.api import local, lcd
import os

#from cStringIO import StringIO
#import gzip
#import binascii
#
#def str2gzipstr(s):
#    buf = StringIO()
#    f = gzip.GzipFile(mode='wb', fileobj=buf)
#    f.write(s)
#    f.close()
#    return buf.getvalue()
#    #return binascii.hexlify(buf.getvalue())

def conhtml():
    '''<usage conhtml>'''
    os.chdir('src')
    fl = os.listdir('.')
    
    html_files = [i for i in fl if i.endswith('.html')]
    
    f_webpage = open('webpage.h', 'w')
    
    s = '''\
    /* Automatically generated by conhtml.py, Do not modify. */
    #ifndef webpage
    #define webpage
    '''
    
    for f_name in html_files:
        f = open(f_name, 'r')
        #s += 'char *%s = "%s";\n'%(f_name.split('.')[0], str2gzipstr(f.read().replace('\n', '').replace('\"', '\'')))
        s += 'char *%s = "%s";\n'%(f_name.split('.')[0], f.read().replace('\n', '\\n').replace('\"', '\''))
        f.close()
    
    s += '#endif'
    
    f_webpage.write(s)
    f_webpage.close()

    os.chdir('..')


def build():
    '''<usage build>'''
    conhtml()
    print 'generate webpage.h '
    local('ino build -m mega2560')
    print '\n'

def upload():
    '''<usage upload>'''
    local('ino upload -m mega2560')


def i():
    build()
    upload()
